apiVersion: v1
kind: Namespace
metadata:
  name: subnetcalc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subnetcalc-pvc
  namespace: subnetcalc
  labels:
    app: subnetcalc
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnetcalc
  namespace: subnetcalc
  labels:
    app: subnetcalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subnetcalc
  template:
    metadata:
      labels:
        app: subnetcalc
    spec:
      containers:
        - name: subnetcalc
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: subnetcalc-html
              mountPath: /usr/share/nginx/html
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi" 
              cpu: "100m"     
            limits:
              memory: "256Mi" 
              cpu: "500m"     
      volumes:
        - name: subnetcalc-html
          persistentVolumeClaim:
            claimName: subnetcalc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: subnetcalc
  namespace: subnetcalc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: subnetcalc