apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: netbox-env-config
            - secretRef:
                name: netbox-env-secrets
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "250Mi" 
              cpu: "250m"     
            limits:
              memory: "500Mi"
              cpu: "500m"  

