apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
spec:
  type: LoadBalancer
  selector:
    app: mealie
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mealie
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
