apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi  # adjust size as needed
