apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"    
          limits:
            memory: "1000Mi"
            cpu: "500m"     
        ports:
        - containerPort: 80
        volumeMounts:
        - name: heimdall-storage
          mountPath: /config
      volumes:
      - name: heimdall-storage
        persistentVolumeClaim:
          claimName: heimdall-pvc
