apiVersion: v1
kind: Namespace
metadata:
  name: rblredwood
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rblredwood-pvc
  namespace: rblredwood
  labels:
    app: rblredwood
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rblredwood
  namespace: rblredwood
  labels:
    app: rblredwood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rblredwood
  template:
    metadata:
      labels:
        app: rblredwood
    spec:
      containers:
        - name: rblredwood
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rblredwood-html
              mountPath: /usr/share/nginx/html
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi" 
              cpu: "100m"     
            limits:
              memory: "256Mi" 
              cpu: "500m"     
      volumes:
        - name: rblredwood-html
          persistentVolumeClaim:
            claimName: rblredwood-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rblredwood
  namespace: rblredwood
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: rblredwood