apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: outline
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: outline-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: outline-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: outline-secrets
              key: POSTGRES_DB
        resources:
          requests:
            memory: "512Mi"   # Memory request for Postgres
            cpu: "250m"       # CPU request for Postgres
          limits:
            memory: "1Gi"     # Memory limit for Postgres
            cpu: "500m"       # CPU limit for Postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
