apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: outline
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"   # Memory request for Redis
            cpu: "100m"       # CPU request for Redis
          limits:
            memory: "512Mi"   # Memory limit for Redis
            cpu: "200m"       # CPU limit for Redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
