apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: uptime-data
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:latest
          resources:
            requests:
              cpu: 250m
              memory: 128Mi          
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: '/app/data'
              name: data-mount
          imagePullPolicy: IfNotPresent