apiVersion: v1
kind: Namespace
metadata:
  name: tikibuggers
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tikibuggers-pvc
  namespace: tikibuggers
  labels:
    app: tikibuggers
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikibuggers
  namespace: tikibuggers
  labels:
    app: tikibuggers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tikibuggers
  template:
    metadata:
      labels:
        app: tikibuggers
    spec:
      containers:
        - name: tikibuggers
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tikibuggers-html
              mountPath: /usr/share/nginx/html
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"    
            limits:
              memory: "256Mi"
              cpu: "500m"    
      volumes:
        - name: tikibuggers-html
          persistentVolumeClaim:
            claimName: tikibuggers-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tikibuggers-service
  namespace: tikibuggers
  labels:
    app: tikibuggers
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tikibuggers
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tikibuggers-ingress
  namespace: tikibuggers
  labels:
    app: tikibuggers
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - tikibuggers.danber.casa
    secretName: tikibuggers-tls
  rules:
  - host: tikibuggers.danber.casa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tikibuggers-service
            port:
              number: 80
# Old way of doing the service for an external IP. No ingress required. 
# Removed this to allow traefik to handle ingress above
# apiVersion: v1
# kind: Service
# metadata:
#   name: tikibuggers
#   namespace: tikibuggers
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: tikibuggers