apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-2-bring-api
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-2-bring-api
  template:
    metadata:
      labels:
        app: mealie-2-bring-api
    spec:
      hostNetwork: true
      containers:
        - name: mealie-2-bring-api
          image: ghcr.io/felixschndr/mealie-bring-api:latest
          ports:
            - containerPort: 8742
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"    
            limits:
              memory: "200Mi"
              cpu: "100m"      
          envFrom:
            - secretRef:
                name: mealie-2-bring-secrets
            - configMapRef:
                name: mealie-2-bring-config                     
