apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-2-bring-api
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-2-bring-api
  template:
    metadata:
      labels:
        app: mealie-2-bring-api
    spec:
      #hostNetwork: true
      containers:
        - name: mealie-2-bring-api
          image: ghcr.io/felixschndr/mealie-bring-api:latest
          ports:
            - containerPort: 8742
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"    
            limits:
              memory: "200Mi"
              cpu: "100m"      
          envFrom:
            - secretRef:
                name: mealie-2-bring-secrets
            - configMapRef:
                name: mealie-2-bring-config                     
---
apiVersion: v1
kind: Service
metadata:
  name: mealie-2-bring-api
  namespace: mealie 
spec:
  selector:
    app: mealie-2-bring-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8742
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: mealie
spec:
  podSelector:
    matchLabels:
      app: mealie-2-bring-api
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # Allows all outbound traffic

