---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBsHSLRYHVan02cBd8mnnvnD4pnNm1lbgQvK2iMPbIAnTjeok5tubbGTMVEUouo7am5McKiJVNskEx6J0p0BdxkzM7iZEXhMH+OmcN1nkkcV/fA60b6F2UnT2p4/v5AVVsaFFxZJj3Ia0NweXO/fbcDI686W8Z/ZZyl382UvmbrpAS855JixtotD2+aVI4H2Q9mUmLZ3AwOLSVvo0g/9JzjW4i2o1sjD0lNFkCL/+yR0zpFidZlPq9yWiZGJyi1mfI0OTjz5cVpelZygTU+3LSfGSPB67cWQEJs8MH2Nf9+NU8TfJrzaeVB5Mz9bk7jEo6Tpmghnms+jTHemvWk7kTTYJzZ4L26ujMrNFz6oVFHUVbNCWCVmCo/BNUdXTwKyp1IsFgyakoCUatqRusHOmJ/kJG5E4ZsyAzugtzv9lyzrbYofQaTcRbq2/tDXesev22nt2dVThtMGUiUjk+rFIOd1BTOSuMuj/FEWEDeTTTwNTNe8PB45TT1a0sEnmGpmbVXyjPI4zMw0SiDl1SOboYj5/QCam0EK19mHkIeG+6Wx9QVNZNO7PSd+Cn5PpS1189K8gjoIdpxwuYVIzu4cNrppKBcCODK2VZxEZl5JxbSU+nFpnj7M0n1TtI2MNefA3ADn8rWeGGNtNXUUJG2jwY4lmRof0KGRecyTeZEm3J0OQIY1GuJJfw2AvasD/pP31t8AvD2Tmz7kr5mB3s2UIs+W7xIm+xc2fddiagiZ+btYWq16co34eZI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
