apiVersion: v1
kind: Namespace
metadata:
  name: shit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shit-pvc
  namespace: shit
  labels:
    app: shit
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shit
  namespace: shit
  labels:
    app: shit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shit
  template:
    metadata:
      labels:
        app: shit
    spec:
      containers:
        - name: shit
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shit-html
              mountPath: /usr/share/nginx/html
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi" 
              cpu: "100m"     
            limits:
              memory: "128Mi"
              cpu: "100m"      
      volumes:
        - name: shit-html
          persistentVolumeClaim:
            claimName: shit-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shit-service
  namespace: shit
  labels:
    app: shit
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: shit
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shit-ingress
  namespace: shit
  labels:
    app: shit
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - shit.danber.casa
    secretName: shit-tls
  rules:
  - host: shit.danber.casa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shit-service
            port:
              number: 80